### ISSUE TITLE
Rotten Tomatoes Review

### ISSUE THREAD

**Issue by marcusellison** [marcusellison/Swift-Rotten-Tomatoes#1]
My app is complete. Please review /cc @codepath

**Comment by codepathreview** [comment]
:+1: Nice work! The point of this homework was to explore a simple example of a full MVC application with a RESTful API. For each point in the homework feedback checklist, I'll either confirm that you're on the right track with the implementation, or I'll provide some feedback:
- As a reminder, there are two great style guides in the
  Swift community like [Ray Wenderlich's Swift Style Guide](https://github.com/raywenderlich/swift-style-guide) and [Github's Swift Style Guide](https://github.com/github/swift-style-guide)
- You can remove generated Xcode functions, if not used (e.g. https://github.com/marcusellison/Swift-Rotten-Tomatoes/blob/4d0a4b92e6a954446bb5c4b62101cbfc6efe583a/Rotten%20Tomatoes/DvdDetailsViewController.swift#L41-L55)
- You should always try to minimize the number of properties and methods that are public or internal (access is internal by default). Make the access private if the property or function doesn't need to be accessed outside the class.
- In future homework, we will cover how to implement models that can deserialize from an NSDictionary. SwiftyJSON is a useful project for making it easier to deserialize the JSON response.
- Nice work with the custom Movie cell! Try to have the cell hold a reference to a Movie model object so it can be more self-contained.
- Nice work loading the images asynchronously.
- Nice work setting up the proper modes for the images so that they are not stretched.
- Nice work implementing the error message on network failure.
  - Try to separate your ViewController code from networking code, this will help keep them more contained and manageable :)

In general, you should challenge yourself to create visually polished applications. That's where you'll find all the rough edges of the iOS framework and earn the next level of mastery.

Feel free to reach out, if you have any questions! I'd be glad to help! :smile:
- @jasdev
